###############################################################################
# ESPHome Addon: ATO (Auto Top-Off) — Raspberry Pi 3B+
# ─────────────────────────────────────────────────────────────────────────────
# MERGE THIS INTO: ~/esphome/fish_tank_temps.yaml
# (Add each section to the matching section in the existing file)
#
# WHAT THIS ADDS TO THE PI:
#   - Float valve input (GPIO17) — detects sump low water
#   - Relay output (GPIO18)      — switches ATO pump on/off
#   - Runtime counter            — hardware safety: kills pump at 120s
#   - HA API services            — allows HA to control relay directly
#
# NOTE ON RESERVOIR TRACKING:
#   Volume tracking (ml per activation, auto-learn) is handled entirely
#   in Home Assistant (fish_tank_ato.yaml). ESPHome only controls hardware.
#   This means HA offline = pump still works via float → relay directly.
#
# ─── GPIO IN USE AFTER MERGING ───────────────────────────────────────────────
#  Pin  GPIO    Function
#  ──────────────────────────────────────────────────────────────────────────
#  1    3.3V    DS18B20 power + pull-up resistor    [existing]
#  2    5V      Relay board VCC                      [NEW]
#  6    GND     DS18B20 ground                       [existing]
#  7    GPIO4   DS18B20 1-wire data (3× temp)        [existing]
#  11   GPIO17  Float valve NC input                 [NEW]
#  12   GPIO18  Relay CH1 → ATO pump                 [NEW]
#  13   GPIO27  RESERVED: future sump height sensor  [reserved]
#  14   GND     Relay board GND + Float common       [NEW]
#
# ─── WIRING: 8-CHANNEL OPTOCOUPLER RELAY BOARD ───────────────────────────────
#  Relay VCC  → Pi Pin 2  (5V)
#  Relay GND  → Pi Pin 14 (GND)
#  Relay IN1  → Pi GPIO18 (Pin 12)
#  Relay COM1 → Pump Live wire (mains or 12V DC depending on pump type)
#  Relay NO1  → Pump supply    (NO = Normally Open = pump OFF when Pi idle)
#
# ─── WIRING: FLOAT VALVE (NC TYPE) ───────────────────────────────────────────
#  Float COM    → Pi Pin 14 (GND)
#  Float NC leg → Pi GPIO17 (Pin 11)
#  + 10kΩ resistor between GPIO17 and 3.3V (Pin 1) as external pull-up
#
#  HOW IT READS:
#    Float UP   (water level OK)  → NC circuit OPEN  → GPIO17 HIGH → no trigger
#    Float DOWN (water level low) → NC circuit CLOSED → GPIO17 LOW  → trigger pump
#
# ─── SAFETY DESIGN ───────────────────────────────────────────────────────────
#  ✅ Relay ACTIVE LOW  → Pi reboot = relay OFF = pump OFF (fail-safe)
#  ✅ Float NC wiring   → broken wire = circuit open = pump stays OFF
#  ✅ restore_mode: ALWAYS_OFF → pump never auto-starts after power cut
#  ✅ 120s hardware cutoff in ESPHome (independent of HA)
#  ✅ HA adds second software safety layer (configurable timeout)
###############################################################################

# ═══════════════════════════════════════════════════════════════════════════════
# MERGE INTO: globals:
# ═══════════════════════════════════════════════════════════════════════════════
# (add these 3 entries inside the existing globals: block)

  - id: ato_pump_runtime_seconds
    type: int
    restore_value: no
    initial_value: '0'

  - id: ato_pump_active
    type: bool
    restore_value: no
    initial_value: 'false'

# ═══════════════════════════════════════════════════════════════════════════════
# MERGE INTO: api: services:
# ═══════════════════════════════════════════════════════════════════════════════
# (add these entries inside the existing api: services: list)

  # Called by HA to manually trigger pump (test runs, overrides)
  - service: ato_pump_on
    then:
      - switch.turn_on: ato_relay_pump

  - service: ato_pump_off
    then:
      - switch.turn_off: ato_relay_pump

# ═══════════════════════════════════════════════════════════════════════════════
# MERGE INTO: sensor:
# ═══════════════════════════════════════════════════════════════════════════════
# (add these entries inside the existing sensor: block)

  # Pump runtime counter — increments every second while pump is on
  # Used by HA to calculate cycle duration for ml-per-activation tracking
  - platform: template
    name: "ATO Pump Runtime This Cycle"
    id: ato_pump_runtime_sensor
    unit_of_measurement: "s"
    icon: mdi:timer
    state_class: measurement
    lambda: |-
      return id(ato_pump_runtime_seconds);
    update_interval: 1s

# ═══════════════════════════════════════════════════════════════════════════════
# NEW SECTION: binary_sensor:
# ═══════════════════════════════════════════════════════════════════════════════
# (add as a new top-level section if binary_sensor: doesn't already exist)

---
binary_sensor:

  # Float valve — NC wiring with external 10kΩ pull-up
  # LOW  (float down, water needed) → triggers pump via HA or direct interval
  # HIGH (float up, water OK)       → pump stops
  - platform: gpio
    pin:
      number: GPIO17
      mode:
        input: true
        pullup: false     # using external 10kΩ pull-up, not internal
      inverted: true      # inverted: NC wiring — LOW = triggered = needs water
    name: "ATO Float Valve"
    id: ato_float_valve
    device_class: moisture
    filters:
      - delayed_on: 5s    # must trigger for 5s before acting (debounce)
      - delayed_off: 3s   # must clear for 3s before stopping pump

  # Pump running indicator (derived from relay state)
  - platform: template
    name: "ATO Pump Running"
    id: ato_pump_running_status
    device_class: running
    lambda: |-
      return id(ato_relay_pump).state;

  # Safety warning — fires when pump has run > 120s
  - platform: template
    name: "ATO Pump Overtime Warning"
    id: ato_pump_overtime
    device_class: problem
    lambda: |-
      return id(ato_pump_runtime_seconds) >= 120;

  # (Future) Sump high water sensor — GPIO27 reserved
  # Uncomment when second float/ultrasonic is wired
  # - platform: gpio
  #   pin:
  #     number: GPIO27
  #     mode:
  #       input: true
  #       pullup: true
  #     inverted: false
  #   name: "Sump High Water Sensor"
  #   id: sump_high_water
  #   device_class: moisture
  #   filters:
  #     - delayed_on: 3s
  #     - delayed_off: 3s

# ═══════════════════════════════════════════════════════════════════════════════
# NEW SECTION: switch:
# ═══════════════════════════════════════════════════════════════════════════════

---
switch:

  # ATO pump relay — active LOW for optocoupler board
  # ALWAYS_OFF: pump will never auto-start after Pi reboot or power cut
  - platform: gpio
    pin:
      number: GPIO18
      inverted: true          # LOW signal activates relay (opto board logic)
    name: "ATO Relay Pump"
    id: ato_relay_pump
    icon: mdi:pump
    restore_mode: ALWAYS_OFF  # ← critical safety: never auto-starts

# ═══════════════════════════════════════════════════════════════════════════════
# NEW SECTION: interval:
# ═══════════════════════════════════════════════════════════════════════════════

---
interval:

  # Ticks every second — tracks runtime and enforces 120s hard cutoff
  # This is the ESPHome safety layer (HA adds a second configurable layer)
  - interval: 1s
    then:
      - if:
          condition:
            switch.is_on: ato_relay_pump
          then:
            - lambda: |-
                id(ato_pump_runtime_seconds) += 1;
                id(ato_pump_active) = true;
            # HARD CUTOFF: kill pump at 120 seconds regardless of float state
            - if:
                condition:
                  lambda: 'return id(ato_pump_runtime_seconds) >= 120;'
                then:
                  - switch.turn_off: ato_relay_pump
                  - logger.log:
                      level: ERROR
                      format: "ATO EMERGENCY STOP — pump exceeded 120s hard limit"
          else:
            # Reset counter when pump is off
            - lambda: |-
                if (id(ato_pump_active)) {
                  id(ato_pump_runtime_seconds) = 0;
                  id(ato_pump_active) = false;
                }

# ═══════════════════════════════════════════════════════════════════════════════
# MERGE INTO: on_boot: (add after existing on_boot entries, or add new)
# ═══════════════════════════════════════════════════════════════════════════════

---
on_boot:
  priority: -100
  then:
    - switch.turn_off: ato_relay_pump   # safety: ensure pump is OFF on every boot
    - lambda: |-
        id(ato_pump_runtime_seconds) = 0;
        id(ato_pump_active) = false;
